#!/usr/bin/env python3

import socket

host = "127.0.0.1"
port = 5001

mySocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
mySocket.connect(("127.0.0.1",5001))

message = input(" ? ")

while message != "q":
    mySocket.send(message.encode("utf-8"))
    data = mySocket.recv(1024).decode("utf-8")

    print("Received from server: " + data)

    message = input(" ? ")

mySocket.close()